### ISSUE TITLE
Mesh view works on paraview 5.12, but has an error on 5.13

### ISSUE THREAD

**Issue by ovo-Tim** [jaheyns/CfdOF#192]
Error output:
```
Qt: Session management error: Could not open network socket
Traceback (most recent call last):
  File "/tmp/download/ParaView-5.13.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/paraview/servermanager.py", line 475, in __setattr__
    setter = getattr(self.__class__, name)
AttributeError: type object 'OpenFOAMReader' has no attribute 'Decomposepolyhedra'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/download/ParaView-5.13.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/paraview/servermanager.py", line 481, in __setattr__
    _bc.setattr(self, name, value)
  File "/tmp/download/ParaView-5.13.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/paraview/_backwardscompatibilityhelper.py", line 523, in setattr
    raise AttributeError()
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/tmp/download/ParaView-5.13.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/paraview/servermanager.py", line 488, in __setattr__
    raise AttributeError("Attribute %s does not exist. " % name +
AttributeError: Attribute Decomposepolyhedra does not exist.  This class does not allow addition of new attributes to avoid mistakes due to typos. Use add_attribute() if you really want to add this attribute.
```

Maybe we should improve `pvScriptMesh.py`, or it's just a bug of paraview.

**Comment by ovo-Tim** [comment]
I also tested nightly verion(`5.13.20241116`), it results in returning the same error.
